name: Python Lint and Test

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        uses: ./.github/workflows/setup_poetry.yml
      - name: Run pylint
        run: poetry run pylint --disable=missing-docstring,redefined-outer-name $(git ls-files '*.py')

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        uses: ./.github/workflows/setup_poetry.yml
      - name: Run pytest
        run: poetry run pytest . -v